variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 0
  GIT_FETCH_EXTRA_ARGS: "--tags --prune --quite"

stages:
  - test
  - release
  
.build-deps: &build-deps
  - apt update -y
  - apt upgrade -y
  - apt install build-essential git librocksdb-dev libsnappy-dev libclang-dev clang g++-multilib protobuf-compiler -y
  - rustup target add wasm32-unknown-unknown
  - rustup component add rust-src --toolchain 1.81.0-x86_64-unknown-linux-gnu

test:
  stage: test
  image: rust:1.81.0-bookworm
  script:
    - *build-deps
    - rustup component add rustfmt clippy
    - cargo install cargo-nextest
    - cargo install zepter
    - ./scripts/check.sh


.debian-repo-setup:
  stage: release
  image: rust:1.81.0-bookworm
  before_script:
   - *build-deps
   - apt install apt-transport-https ca-certificates gnupg curl -y
   - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
   - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
   - apt update -y && apt install google-cloud-cli -y
   - cargo install cargo-deb
   - gcloud auth activate-service-account --key-file $GCP_DEB_DEPLOY_JSON_KEY
   - gcloud config set core/project dlabs-317612
   - gcloud config set artifacts/location europe-west3
   - gcloud config set artifacts/repository deb-repo

debian-solo-rc:
  extends: .debian-repo-setup
  only:
    - develop
  script:
    - PKG=$(cargo deb -p mosaic-testnet-solo-node --profile release --variant rc --deb-version $(git describe --tags --match "[0-9]*" --always --dirty | sed "s/-/+/g"))
    - gcloud artifacts apt upload deb-repo --source $PKG

debian-solo-release:
  extends: .debian-repo-setup
  only:
    - main
  script:
    - PKG=$(cargo deb -p mosaic-testnet-solo-node --profile release --variant release)
    - gcloud artifacts apt upload deb-repo --source $PKG
   
debian-para-rc:
  extends: .debian-repo-setup
  only:
    - develop
  script:
    - PKG=$(cargo deb -p mosaic-chain-node --profile release --variant rc --deb-version $(git describe --tags --match "[0-9]*" --always --dirty | sed "s/-/+/g"))
    - gcloud artifacts apt upload deb-repo --source $PKG

debian-para-release:
  extends: .debian-repo-setup
  only:
    - main
  script:
    - PKG=$(cargo deb -p mosaic-chain-node --profile release --variant release)
    - gcloud artifacts apt upload deb-repo --source $PKG

.docker:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  variables:
    GCP_URL: europe-west3-docker.pkg.dev
    GCP_REGISTRY: $GCP_URL/dlabs-317612/docker-registry
  script:
    # Build GitLab images
    - docker build -f Dockerfile.testnet-solo-local -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG -t $GCP_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
   
    # Login to GitLab registry
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

    # Push GitLab image
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG

    # Login to GCP registry
    - docker login -u _json_key --password-stdin https://$GCP_URL <$GCP_DEPLOY_JSON_KEY

    # Push GCP image
    - docker push $GCP_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

solo-local-docker-rc:
  extends: .docker
  variables:
    IMAGE_NAME: mosaic-chain-solo-local
    IMAGE_TAG: rc
  only:
    - develop

solo-local-docker-latest:
  extends: .docker
  variables:
    IMAGE_NAME: mosaic-chain-solo-local
    IMAGE_TAG: latest
  only:
    - main
