stages:
  - test
  - release

all-in-one-tests:
  stage: test
  image: rust:bookworm
  script:
    - apt update -y
    - apt upgrade -y
    - apt install build-essential git librocksdb-dev libsnappy-dev libclang-dev clang g++-multilib protobuf-compiler -y
    - rustup target add wasm32-unknown-unknown
    - rustup component add rustfmt clippy
    - cargo install cargo-nextest
    - cargo fmt -- --check
    - cargo clippy --color=always --tests --examples --bins --benches --release --features runtime-benchmarks,try-runtime --no-deps -- -D warnings
    - cargo nextest run --release --features try-runtime

docker-rc:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  only:
    - develop
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f Dockerfile -t $CI_REGISTRY_IMAGE/mosaic-chain:rc .
    - docker push $CI_REGISTRY_IMAGE/mosaic-chain:rc

docker-latest:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  only:
    - main
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f Dockerfile -t $CI_REGISTRY_IMAGE/mosaic-chain:latest .
    - docker push $CI_REGISTRY_IMAGE/mosaic-chain:latest
