variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 0
  GIT_FETCH_EXTRA_ARGS: "--tags --prune --quiet"

stages:
  - test
  - release

.build-deps: &build-deps
  - apt update -y
  - apt upgrade -y
  - apt install build-essential git librocksdb-dev libsnappy-dev libclang-dev clang g++-multilib protobuf-compiler -y
  - rustup target add wasm32-unknown-unknown
  - rustup component add rust-src --toolchain 1.81.0-x86_64-unknown-linux-gnu

test:
  stage: test
  image: rust:1.81.0-bookworm
  script:
    - *build-deps
    - rustup component add rustfmt clippy
    - cargo install --locked cargo-nextest@0.9.97-b.2
    - cargo install --locked cargo-deny@0.17.0
    - cargo install --locked zepter
    - ./scripts/check.sh

benchmark:
  stage: test
  when: manual
  image: rust:1.81.0-bookworm
  before_script:
    - apt update
    - apt install jq -y
    - mkdir -p ~/.ssh
    - ssh-keygen -t rsa -q -f ~/.ssh/id_rsa -N ""
    - export GITLAB_CI_PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub)

    - >
      curl --fail-with-body \
        -X POST \
        -H "Authorization: Bearer $HETZNER_API_KEY" \
        -H "Content-Type: application/json" \
        -d "{\"name\":\"mosaic-chain-benchmark-$CI_COMMIT_SHORT_SHA\",\"public_key\":\"$GITLAB_CI_PUBLIC_KEY\"}" \
        "https://api.hetzner.cloud/v1/ssh_keys" > ./create_ssh_key_response
    - export HETZNER_SSH_KEY_ID=$(cat ./create_ssh_key_response | jq -r '.ssh_key.id')
    - >
      curl --fail-with-body \
        -H "Authorization: Bearer $HETZNER_API_KEY" \
        -H "Content-Type: application/json" \
        -d "{ \"name\": \"mosaic-chain-benchmark-$CI_COMMIT_SHORT_SHA\", \"server_type\": \"cpx41\", \"location\": \"nbg1\", \"image\": \"debian-12\", \"ssh_keys\": [ $HETZNER_SSH_KEY_ID ] }" \
        -X POST \
        'https://api.hetzner.cloud/v1/servers' > ./create_server_response
    - export HETZNER_SERVER_ID=$(cat ./create_server_response | jq -r '.server.id')
    - export HETZNER_SERVER_IP=$(cat ./create_server_response | jq -r '.server.public_net.ipv4.ip')
    - 'echo "Created server with ID: $HETZNER_SERVER_ID"'

  after_script:
    - export HETZNER_SSH_KEY_ID=$(cat ./create_ssh_key_response | jq -r '.ssh_key.id')
    - >
      curl --fail-with-body \
        -H "Authorization: Bearer $HETZNER_API_KEY" \
        -X DELETE \
        "https://api.hetzner.cloud/v1/ssh_keys/$HETZNER_SSH_KEY_ID"
    - export HETZNER_SERVER_ID=$(cat ./create_server_response | jq -r '.server.id')
    - >
      curl --fail-with-body \
        -H "Authorization: Bearer $HETZNER_API_KEY" \
        -X DELETE \
        "https://api.hetzner.cloud/v1/servers/$HETZNER_SERVER_ID"

  script:
    - *build-deps
    - cargo install cargo-deb
    - PKG=$(cargo deb -p mosaic-chain-node --profile release --variant benchmark)

    - ssh-keyscan -H $HETZNER_SERVER_IP >> ~/.ssh/known_hosts
    - "scp $PKG root@$HETZNER_SERVER_IP:~/benchmark.deb"
    - ssh root@$HETZNER_SERVER_IP "dpkg --install ~/benchmark.deb && benchmark-runtime"
    - "scp -r $HETZNER_SERVER_IP:~/weights/* ./runtime/parachain/src/weights/pallet/"

    - git config user.email "update-benchmark-weights-bot@dlabs.hu"
    - git config user.name "Update Benchmark Weights Bot"
    - git remote set-url --push origin "https://gitlab-ci:$GITLAB_CI_ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    - git add ./runtime/parachain/src/weights/pallet
    - git commit -m 'Update benchmark weights'
    - git push origin HEAD:$CI_COMMIT_REF_NAME

.debian-repo-setup:
  stage: release
  image: rust:1.81.0-bookworm
  before_script:
    - *build-deps
    - apt install apt-transport-https ca-certificates gnupg curl -y
    - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
    - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    - apt update -y && apt install google-cloud-cli -y
    - cargo install cargo-deb
    - gcloud auth activate-service-account --key-file $GCP_STAGING_ARTIFACT_WRITE_JSON_KEY
    - gcloud config set core/project mosaicchan-devnet
    - gcloud config set artifacts/location europe
    - gcloud config set artifacts/repository apt-staging-repository

debian-testnet:
  extends: .debian-repo-setup
  only:
    - testnet
  script:
    - PKG=$(cargo deb -p mosaic-testnet-solo-node --profile release)
    - gcloud artifacts apt upload apt-staging-repository --source $PKG

debian-devnet:
  extends: .debian-repo-setup
  only:
    - devnet
  script:
    - PKG=$(cargo deb -p mosaic-chain-node --profile release --variant devnet)
    - gcloud artifacts apt upload apt-staging-repository --source $PKG

debian-mainnet:
  extends: .debian-repo-setup
  only:
    - mainnet
  script:
    - PKG=$(cargo deb -p mosaic-chain-node --profile release --variant mainnet)
    - gcloud artifacts apt upload apt-staging-repository --source $PKG

.docker:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  variables:
    GCP_URL: europe-docker.pkg.dev
    GCP_REGISTRY: $GCP_URL/mosaicchan-devnet/docker-staging-registry
  script:
    # Build GitLab images
    - docker build -f Dockerfile.testnet-solo-local -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG -t $GCP_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

    # Login to GitLab registry
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

    # Push GitLab image
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG

    # Login to GCP registry
    - docker login -u _json_key --password-stdin https://$GCP_URL <$GCP_STAGING_ARTIFACT_WRITE_JSON_KEY

    # Push GCP image
    - docker push $GCP_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

solo-local-docker:
  extends: .docker
  variables:
    IMAGE_NAME: mosaic-chain-solo-local
    IMAGE_TAG: rc
  only:
    - testnet
