[advisories]
version = 2
yanked = "warn"
ignore = [
    "RUSTSEC-2024-0384", # `instant` is unmaintained
    "RUSTSEC-2020-0168", # `mach` is unmaintained
    "RUSTSEC-2022-0061", # `parity-wasm` is deprecated 🤦
    "RUSTSEC-2024-0436", # `paste` is unmaintained
    "RUSTSEC-2024-0370", # `proc-macro-error` is unmaintained
    "RUSTSEC-2024-0438", # `wasmtime` doesn't fully sandbox all the Windows device filenames
    "RUSTSEC-2023-0091", # `wasmtime` miscompilation of wasm `i64x2.shr_s` instruction with constant input on x86\_64
    "RUSTSEC-2024-0442", # safe code can leak memory in `wasmtime-jit-debug`
    "RUSTSEC-2025-0057", # `fxhash` is unmaintained
    "RUSTSEC-2025-0118", # wasmtime linear memory is not used from multiple threads
    "RUSTSEC-2026-0002", # TODO: update polkadot-sdk when this (lru) is fixed there
    "RUSTSEC-2025-0141", # TODO: update polkadot-sdk when bincode is replaced by an alternative
]

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "MIT",
    "MIT-0",
    "ISC",
    "Unicode-3.0",
    "Zlib",
    # copyleft:
    "GPL-3.0-or-later",                              # this makes our nodes GPL-3.0, too
    "GPL-3.0-only",                                  # this makes our nodes GPL-3.0, too
    "GPL-3.0-or-later WITH Classpath-exception-2.0", # like LGPL, but legally simpler
    "MPL-2.0",                                       # other source code files can use any license
]
confidence-threshold = 0.8
exceptions = [
    #{ allow = ["Zlib"], name = "adler32", version = "*" },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[licenses.private]
ignore = false

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true
highlight = "all"
allow = [
    #{ name = "ansi_term", version = "=0.11.0" },
]
deny = [
    #{ name = "ansi_term", version = "=0.11.0", wrappers = [] },
]
skip = [
    #duplicates
    { name = "addr2line" },
    { name = "arrayvec" },
    { name = "async-channel" },
    { name = "async-io" },
    { name = "async-lock" },
    { name = "base64" },
    { name = "bitflags" },
    { name = "blake2" },
    { name = "block-buffer" },
    { name = "cargo_metadata" },
    { name = "cfg_aliases" },
    { name = "cipher" },
    { name = "constant_time_eq" },
    { name = "core-foundation" },
    { name = "crypto-mac" },
    { name = "derive_more" },
    { name = "digest" },
    { name = "env_logger" },
    { name = "event-listener" },
    { name = "fastrand" },
    { name = "frame-metadata" },
    { name = "generic-array" },
    { name = "getrandom" },
    { name = "heck" },
    { name = "hmac" },
    { name = "itertools" },
    { name = "lru" },
    { name = "memmap2" },
    { name = "multiaddr" },
    { name = "nix" },
    { name = "pallet-treasury", reason = "We forked an older version" },
    { name = "schnorrkel" },
    { name = "semver" },
    { name = "sp-crypto-hashing" },
    { name = "windows-core" },
    { name = "yamux" },
    { name = "windows-result" },
]
skip-tree = [
    # duplicate mess
    { name = "asn1-rs" },
    { name = "cid" },
    { name = "darling" },
    { name = "smol" },
    { name = "gimli" },
    { name = "hyper-rustls" },
    { name = "primitive-types" },
    { name = "jsonrpsee" },
    { name = "wasmtime" },
    { name = "mockall" },
    { name = "prost" },
    { name = "strum" },
]

[bans.workspace-dependencies]
duplicates = 'deny'
include-path-dependencies = true
unused = 'deny'

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/Mosaic-Chain/polkadot-sdk?branch=unsafe-warp-sync-2506-1"]

[sources.allow-org]
#github = ["wigy_opensource_developer"]
#gitlab = [""]
#bitbucket = [""]
