FROM rust:bookworm

RUN apt update -y \
    && apt upgrade -y \
    && apt install build-essential git librocksdb-dev libsnappy-dev libclang-dev clang g++-multilib protobuf-compiler mold -y

RUN rustup target add wasm32-unknown-unknown
RUN rustup component add rustfmt clippy
RUN cargo install cargo-nextest --locked

WORKDIR /opt/app
COPY . .

ENV RUSTFLAGS=-Dwarnings

RUN cargo fmt -- --check

RUN cargo clippy --color=always --tests --examples --bins --benches --features runtime-benchmarks,try-runtime

# Does this add any relevant tests? We should use `mosaic-chain benchmark pallet`
# anyways, where the binary is built with the `runtime-benchmarks` feature.
#RUN cargo test --release --features runtime-benchmarks

RUN cargo nextest run --release --features try-runtime
