
//! Autogenerated weights for `pallet_collective`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-04-23, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `mosaic-chain-benchmark-d786f86b`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// mosaic-chain-benchmark
// benchmark
// pallet
// --pallet
// pallet-collective
// --extrinsic
// *
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --output
// weights/collective.rs
// --template
// /usr/share/mosaic-chain-benchmark/benchmark-runtime-weights.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

use sdk::*;

use pallet_collective::weights::WeightInfo;


/// Weights for `pallet_collective` using the recommended hardware.
pub struct Weights<T>(PhantomData<T>);
impl<T: sdk::frame_system::Config> WeightInfo for Weights<T> {
	/// Storage: `CouncilCollective::Members` (r:1 w:1)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Proposals` (r:1 w:0)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Voting` (r:10 w:10)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Prime` (r:0 w:1)
	/// Proof: `CouncilCollective::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[0, 100]`.
	/// The range of component `n` is `[0, 100]`.
	/// The range of component `p` is `[0, 10]`.
	fn set_members(m: u32, _n: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (352 ±0) + p * (3191 ±0)`
		//  Estimated: `10018 + m * (223 ±3) + p * (3967 ±30)`
		// Minimum execution time: 16_870_000 picoseconds.
		Weight::from_parts(17_100_000, 10018)
			// Standard Error: 9_083
			.saturating_add(Weight::from_parts(656_183, 0).saturating_mul(m.into()))
			// Standard Error: 88_720
			.saturating_add(Weight::from_parts(10_817_591, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(p.into())))
			.saturating_add(Weight::from_parts(0, 223).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 3967).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 100]`.
	fn execute(b: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `31 + m * (32 ±0)`
		//  Estimated: `1517 + m * (32 ±0)`
		// Minimum execution time: 14_950_000 picoseconds.
		Weight::from_parts(15_387_138, 1517)
			// Standard Error: 84
			.saturating_add(Weight::from_parts(839, 0).saturating_mul(b.into()))
			// Standard Error: 872
			.saturating_add(Weight::from_parts(16_740, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(m.into()))
	}
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalOf` (r:1 w:0)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 100]`.
	fn propose_execute(b: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `31 + m * (32 ±0)`
		//  Estimated: `3497 + m * (32 ±0)`
		// Minimum execution time: 18_170_000 picoseconds.
		Weight::from_parts(18_994_322, 3497)
			// Standard Error: 105
			.saturating_add(Weight::from_parts(1_128, 0).saturating_mul(b.into()))
			// Standard Error: 1_088
			.saturating_add(Weight::from_parts(21_338, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(m.into()))
	}
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalOf` (r:1 w:1)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalCount` (r:1 w:1)
	/// Proof: `CouncilCollective::ProposalCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Parameters::Parameters` (r:1 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `CouncilCollective::Voting` (r:0 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[2, 100]`.
	/// The range of component `p` is `[1, 10]`.
	fn propose_proposed(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `128 + m * (32 ±0) + p * (56 ±0)`
		//  Estimated: `3502 + m * (32 ±0) + p * (62 ±0)`
		// Minimum execution time: 28_660_000 picoseconds.
		Weight::from_parts(27_308_906, 3502)
			// Standard Error: 119
			.saturating_add(Weight::from_parts(2_499, 0).saturating_mul(b.into()))
			// Standard Error: 1_246
			.saturating_add(Weight::from_parts(31_452, 0).saturating_mul(m.into()))
			// Standard Error: 12_738
			.saturating_add(Weight::from_parts(656_448, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 62).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Voting` (r:1 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[5, 100]`.
	fn vote(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `365 + m * (64 ±0)`
		//  Estimated: `3829 + m * (64 ±0)`
		// Minimum execution time: 20_830_000 picoseconds.
		Weight::from_parts(22_037_942, 3829)
			// Standard Error: 800
			.saturating_add(Weight::from_parts(54_812, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(m.into()))
	}
	/// Storage: `CouncilCollective::Voting` (r:1 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalOf` (r:0 w:1)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 10]`.
	fn close_early_disapproved(m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `134 + m * (64 ±0) + p * (54 ±0)`
		//  Estimated: `3607 + m * (64 ±0) + p * (53 ±0)`
		// Minimum execution time: 30_660_000 picoseconds.
		Weight::from_parts(28_172_711, 3607)
			// Standard Error: 857
			.saturating_add(Weight::from_parts(43_946, 0).saturating_mul(m.into()))
			// Standard Error: 8_670
			.saturating_add(Weight::from_parts(421_319, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 53).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::Voting` (r:1 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalOf` (r:1 w:1)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 10]`.
	fn close_early_approved(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140 + b * (1 ±0) + m * (64 ±0) + p * (83 ±0)`
		//  Estimated: `3588 + b * (1 ±0) + m * (64 ±0) + p * (86 ±0)`
		// Minimum execution time: 43_280_000 picoseconds.
		Weight::from_parts(38_946_889, 3588)
			// Standard Error: 92
			.saturating_add(Weight::from_parts(1_286, 0).saturating_mul(b.into()))
			// Standard Error: 973
			.saturating_add(Weight::from_parts(54_324, 0).saturating_mul(m.into()))
			// Standard Error: 9_817
			.saturating_add(Weight::from_parts(568_681, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 1).saturating_mul(b.into()))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 86).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::Voting` (r:1 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Prime` (r:1 w:0)
	/// Proof: `CouncilCollective::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalOf` (r:0 w:1)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 10]`.
	fn close_disapproved(m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `232 + m * (48 ±0) + p * (54 ±0)`
		//  Estimated: `3699 + m * (48 ±0) + p * (54 ±0)`
		// Minimum execution time: 32_280_000 picoseconds.
		Weight::from_parts(29_661_343, 3699)
			// Standard Error: 810
			.saturating_add(Weight::from_parts(46_003, 0).saturating_mul(m.into()))
			// Standard Error: 8_197
			.saturating_add(Weight::from_parts(449_724, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 48).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 54).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::Voting` (r:1 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Prime` (r:1 w:0)
	/// Proof: `CouncilCollective::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalOf` (r:1 w:1)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 10]`.
	fn close_approved(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `160 + b * (1 ±0) + m * (64 ±0) + p * (83 ±0)`
		//  Estimated: `3608 + b * (1 ±0) + m * (64 ±0) + p * (86 ±0)`
		// Minimum execution time: 45_530_000 picoseconds.
		Weight::from_parts(41_996_018, 3608)
			// Standard Error: 108
			.saturating_add(Weight::from_parts(808, 0).saturating_mul(b.into()))
			// Standard Error: 1_144
			.saturating_add(Weight::from_parts(50_175, 0).saturating_mul(m.into()))
			// Standard Error: 11_545
			.saturating_add(Weight::from_parts(613_534, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 1).saturating_mul(b.into()))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 86).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Voting` (r:0 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalOf` (r:0 w:1)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `p` is `[1, 10]`.
	fn disapprove_proposal(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `188 + p * (32 ±0)`
		//  Estimated: `1673 + p * (32 ±0)`
		// Minimum execution time: 14_830_000 picoseconds.
		Weight::from_parts(15_597_197, 1673)
			// Standard Error: 4_497
			.saturating_add(Weight::from_parts(359_076, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::ProposalOf` (r:1 w:1)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::CostOf` (r:1 w:0)
	/// Proof: `CouncilCollective::CostOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Voting` (r:0 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `d` is `[0, 1]`.
	/// The range of component `p` is `[1, 10]`.
	fn kill(d: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1243 + p * (57 ±0)`
		//  Estimated: `4708 + p * (57 ±0)`
		// Minimum execution time: 23_150_000 picoseconds.
		Weight::from_parts(24_458_113, 4708)
			// Standard Error: 37_912
			.saturating_add(Weight::from_parts(170_864, 0).saturating_mul(d.into()))
			// Standard Error: 6_088
			.saturating_add(Weight::from_parts(488_012, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 57).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::ProposalOf` (r:1 w:0)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::CostOf` (r:1 w:0)
	/// Proof: `CouncilCollective::CostOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn release_proposal_cost() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `436`
		//  Estimated: `3901`
		// Minimum execution time: 12_250_000 picoseconds.
		Weight::from_parts(12_920_000, 3901)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
}
