
//! Autogenerated weights for `pallet_collective`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2025-10-03, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `mosaic-chain-benchmark-68e88b2d`, CPU: `AMD EPYC-Rome Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// mosaic-chain-benchmark
// benchmark
// pallet
// --pallet
// pallet-collective
// --extrinsic
// *
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --output
// weights/collective.rs
// --template
// /usr/share/mosaic-chain-benchmark/benchmark-runtime-weights.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

use sdk::*;

use pallet_collective::weights::WeightInfo;


/// Weights for `pallet_collective` using the recommended hardware.
pub struct Weights<T>(PhantomData<T>);
impl<T: sdk::frame_system::Config> WeightInfo for Weights<T> {
	/// Storage: `CouncilCollective::Members` (r:1 w:1)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Proposals` (r:1 w:0)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Voting` (r:10 w:10)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Prime` (r:0 w:1)
	/// Proof: `CouncilCollective::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[0, 100]`.
	/// The range of component `n` is `[0, 100]`.
	/// The range of component `p` is `[0, 10]`.
	fn set_members(m: u32, _n: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (352 ±0) + p * (3191 ±0)`
		//  Estimated: `10018 + m * (223 ±3) + p * (3967 ±30)`
		// Minimum execution time: 21_481_000 picoseconds.
		Weight::from_parts(21_621_000, 10018)
			// Standard Error: 10_790
			.saturating_add(Weight::from_parts(742_668, 0).saturating_mul(m.into()))
			// Standard Error: 105_394
			.saturating_add(Weight::from_parts(12_189_597, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(p.into())))
			.saturating_add(Weight::from_parts(0, 223).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 3967).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 100]`.
	fn execute(b: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `31 + m * (32 ±0)`
		//  Estimated: `1517 + m * (32 ±0)`
		// Minimum execution time: 19_557_000 picoseconds.
		Weight::from_parts(20_215_816, 1517)
			// Standard Error: 364
			.saturating_add(Weight::from_parts(3_446, 0).saturating_mul(b.into()))
			// Standard Error: 3_752
			.saturating_add(Weight::from_parts(15_326, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(m.into()))
	}
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalOf` (r:1 w:0)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 100]`.
	fn propose_execute(b: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `31 + m * (32 ±0)`
		//  Estimated: `3497 + m * (32 ±0)`
		// Minimum execution time: 24_186_000 picoseconds.
		Weight::from_parts(21_225_010, 3497)
			// Standard Error: 448
			.saturating_add(Weight::from_parts(3_815, 0).saturating_mul(b.into()))
			// Standard Error: 4_624
			.saturating_add(Weight::from_parts(77_606, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(m.into()))
	}
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalOf` (r:1 w:1)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalCount` (r:1 w:1)
	/// Proof: `CouncilCollective::ProposalCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Parameters::Parameters` (r:1 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `CouncilCollective::Voting` (r:0 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[2, 100]`.
	/// The range of component `p` is `[1, 10]`.
	fn propose_proposed(_b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `128 + m * (32 ±0) + p * (56 ±0)`
		//  Estimated: `3502 + m * (32 ±0) + p * (62 ±0)`
		// Minimum execution time: 35_826_000 picoseconds.
		Weight::from_parts(41_392_571, 3502)
			// Standard Error: 4_400
			.saturating_add(Weight::from_parts(21_664, 0).saturating_mul(m.into()))
			// Standard Error: 44_958
			.saturating_add(Weight::from_parts(612_954, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 62).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Voting` (r:1 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[5, 100]`.
	fn vote(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `365 + m * (64 ±0)`
		//  Estimated: `3829 + m * (64 ±0)`
		// Minimum execution time: 25_967_000 picoseconds.
		Weight::from_parts(27_817_858, 3829)
			// Standard Error: 3_539
			.saturating_add(Weight::from_parts(46_610, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(m.into()))
	}
	/// Storage: `CouncilCollective::Voting` (r:1 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalOf` (r:0 w:1)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 10]`.
	fn close_early_disapproved(m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `134 + m * (64 ±0) + p * (54 ±0)`
		//  Estimated: `3607 + m * (64 ±0) + p * (53 ±0)`
		// Minimum execution time: 36_749_000 picoseconds.
		Weight::from_parts(35_159_688, 3607)
			// Standard Error: 3_717
			.saturating_add(Weight::from_parts(46_167, 0).saturating_mul(m.into()))
			// Standard Error: 37_594
			.saturating_add(Weight::from_parts(472_606, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 53).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::Voting` (r:1 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalOf` (r:1 w:1)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 10]`.
	fn close_early_approved(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140 + b * (1 ±0) + m * (64 ±0) + p * (83 ±0)`
		//  Estimated: `3588 + b * (1 ±0) + m * (64 ±0) + p * (86 ±0)`
		// Minimum execution time: 51_726_000 picoseconds.
		Weight::from_parts(43_230_705, 3588)
			// Standard Error: 757
			.saturating_add(Weight::from_parts(3_517, 0).saturating_mul(b.into()))
			// Standard Error: 8_003
			.saturating_add(Weight::from_parts(90_088, 0).saturating_mul(m.into()))
			// Standard Error: 80_723
			.saturating_add(Weight::from_parts(835_191, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 1).saturating_mul(b.into()))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 86).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::Voting` (r:1 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Prime` (r:1 w:0)
	/// Proof: `CouncilCollective::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalOf` (r:0 w:1)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 10]`.
	fn close_disapproved(m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `232 + m * (48 ±0) + p * (54 ±0)`
		//  Estimated: `3699 + m * (48 ±0) + p * (54 ±0)`
		// Minimum execution time: 38_621_000 picoseconds.
		Weight::from_parts(41_391_074, 3699)
			// Standard Error: 6_082
			.saturating_add(Weight::from_parts(15_596, 0).saturating_mul(m.into()))
			// Standard Error: 61_505
			.saturating_add(Weight::from_parts(462_731, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 48).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 54).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::Voting` (r:1 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Members` (r:1 w:0)
	/// Proof: `CouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Prime` (r:1 w:0)
	/// Proof: `CouncilCollective::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalOf` (r:1 w:1)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 10]`.
	fn close_approved(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `160 + b * (1 ±0) + m * (64 ±0) + p * (83 ±0)`
		//  Estimated: `3608 + b * (1 ±0) + m * (64 ±0) + p * (86 ±0)`
		// Minimum execution time: 54_321_000 picoseconds.
		Weight::from_parts(61_837_199, 3608)
			// Standard Error: 5_610
			.saturating_add(Weight::from_parts(8_817, 0).saturating_mul(m.into()))
			// Standard Error: 56_590
			.saturating_add(Weight::from_parts(353_924, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 1).saturating_mul(b.into()))
			.saturating_add(Weight::from_parts(0, 64).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 86).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Voting` (r:0 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::ProposalOf` (r:0 w:1)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `p` is `[1, 10]`.
	fn disapprove_proposal(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `188 + p * (32 ±0)`
		//  Estimated: `1673 + p * (32 ±0)`
		// Minimum execution time: 19_236_000 picoseconds.
		Weight::from_parts(20_894_683, 1673)
			// Standard Error: 32_454
			.saturating_add(Weight::from_parts(415_028, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::ProposalOf` (r:1 w:1)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::CostOf` (r:1 w:0)
	/// Proof: `CouncilCollective::CostOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `CouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::Voting` (r:0 w:1)
	/// Proof: `CouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `d` is `[0, 1]`.
	/// The range of component `p` is `[1, 10]`.
	fn kill(_d: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1243 + p * (57 ±0)`
		//  Estimated: `4708 + p * (57 ±0)`
		// Minimum execution time: 29_094_000 picoseconds.
		Weight::from_parts(33_496_811, 4708)
			// Standard Error: 18_558
			.saturating_add(Weight::from_parts(245_771, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 57).saturating_mul(p.into()))
	}
	/// Storage: `CouncilCollective::ProposalOf` (r:1 w:0)
	/// Proof: `CouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilCollective::CostOf` (r:1 w:0)
	/// Proof: `CouncilCollective::CostOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn release_proposal_cost() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `436`
		//  Estimated: `3901`
		// Minimum execution time: 14_577_000 picoseconds.
		Weight::from_parts(15_249_000, 3901)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
}
