
//! Autogenerated weights for `pallet_hold_vesting`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2025-09-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `mosaic-chain-benchmark-463804d1`, CPU: `AMD EPYC-Rome Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// mosaic-chain-benchmark
// benchmark
// pallet
// --pallet
// pallet-hold-vesting
// --extrinsic
// *
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --output
// weights/hold_vesting.rs
// --template
// /usr/share/mosaic-chain-benchmark/benchmark-runtime-weights.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

use sdk::*;

use pallet_hold_vesting::weights::WeightInfo;


/// Weights for `pallet_hold_vesting` using the recommended hardware.
pub struct Weights<T>(PhantomData<T>);
impl<T: sdk::frame_system::Config> WeightInfo for Weights<T> {
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: Some(345), added: 2820, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(697), added: 3172, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn vest_locked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `4162`
		// Minimum execution time: 18_860_000 picoseconds.
		Weight::from_parts(18_925_502, 4162)
			// Standard Error: 20_824
			.saturating_add(Weight::from_parts(194_698, 0).saturating_mul(l.into()))
			// Standard Error: 12_718
			.saturating_add(Weight::from_parts(315_673, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: Some(345), added: 2820, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(697), added: 3172, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn vest_unlocked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `4162`
		// Minimum execution time: 50_180_000 picoseconds.
		Weight::from_parts(49_454_692, 4162)
			// Standard Error: 32_697
			.saturating_add(Weight::from_parts(662_526, 0).saturating_mul(l.into()))
			// Standard Error: 19_968
			.saturating_add(Weight::from_parts(414_499, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: Some(345), added: 2820, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(697), added: 3172, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn vest_other_locked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `4162`
		// Minimum execution time: 18_610_000 picoseconds.
		Weight::from_parts(20_645_374, 4162)
			// Standard Error: 59_525
			.saturating_add(Weight::from_parts(315_593, 0).saturating_mul(l.into()))
			// Standard Error: 36_353
			.saturating_add(Weight::from_parts(52_475, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: Some(345), added: 2820, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(697), added: 3172, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn vest_other_unlocked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `383 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `4162`
		// Minimum execution time: 52_850_000 picoseconds.
		Weight::from_parts(55_255_338, 4162)
			// Standard Error: 50_393
			.saturating_add(Weight::from_parts(525_088, 0).saturating_mul(l.into()))
			// Standard Error: 30_776
			.saturating_add(Weight::from_parts(63_479, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: Some(345), added: 2820, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(697), added: 3172, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 7]`.
	fn vested_transfer(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `383 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `4162`
		// Minimum execution time: 98_069_000 picoseconds.
		Weight::from_parts(99_713_652, 4162)
			// Standard Error: 50_386
			.saturating_add(Weight::from_parts(21_466, 0).saturating_mul(l.into()))
			// Standard Error: 34_975
			.saturating_add(Weight::from_parts(472_499, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: Some(345), added: 2820, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(697), added: 3172, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 7]`.
	fn force_vested_transfer(_l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `486 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `6196`
		// Minimum execution time: 99_440_000 picoseconds.
		Weight::from_parts(102_123_168, 6196)
			// Standard Error: 43_402
			.saturating_add(Weight::from_parts(582_169, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: Some(345), added: 2820, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(697), added: 3172, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[2, 8]`.
	fn not_unlocking_merge_schedules(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `4162`
		// Minimum execution time: 19_350_000 picoseconds.
		Weight::from_parts(19_354_673, 4162)
			// Standard Error: 15_893
			.saturating_add(Weight::from_parts(312_780, 0).saturating_mul(l.into()))
			// Standard Error: 11_032
			.saturating_add(Weight::from_parts(278_056, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: Some(345), added: 2820, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(697), added: 3172, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[2, 8]`.
	fn unlocking_merge_schedules(_l: u32, _s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `310 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `4162`
		// Minimum execution time: 51_930_000 picoseconds.
		Weight::from_parts(57_727_744, 4162)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: Some(345), added: 2820, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(697), added: 3172, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[2, 8]`.
	fn force_remove_vesting_schedule(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `383 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `4162`
		// Minimum execution time: 53_130_000 picoseconds.
		Weight::from_parts(53_550_259, 4162)
			// Standard Error: 17_591
			.saturating_add(Weight::from_parts(159_069, 0).saturating_mul(l.into()))
			// Standard Error: 12_210
			.saturating_add(Weight::from_parts(274_569, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: Some(345), added: 2820, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(697), added: 3172, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn start_vesting_schedule_unlocked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `379 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `4162`
		// Minimum execution time: 52_960_000 picoseconds.
		Weight::from_parts(53_913_314, 4162)
			// Standard Error: 39_696
			.saturating_add(Weight::from_parts(353_046, 0).saturating_mul(l.into()))
			// Standard Error: 24_243
			.saturating_add(Weight::from_parts(199_400, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: Some(345), added: 2820, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(697), added: 3172, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn start_vesting_schedule_locked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `205 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `4162`
		// Minimum execution time: 18_520_000 picoseconds.
		Weight::from_parts(18_255_887, 4162)
			// Standard Error: 12_952
			.saturating_add(Weight::from_parts(369_039, 0).saturating_mul(l.into()))
			// Standard Error: 7_910
			.saturating_add(Weight::from_parts(278_026, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}
