
//! Autogenerated weights for `pallet_staking_incentive`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-02-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `mosaic-chain-benchmark-de579aec`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// mosaic-chain-benchmark
// benchmark
// pallet
// --pallet
// pallet-staking-incentive
// --extrinsic
// *
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --output
// weights/staking_incentive.rs
// --template
// /usr/share/mosaic-chain-benchmark/benchmark-runtime-weights.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

use sdk::*;

use pallet_staking_incentive::weights::WeightInfo;


/// Weights for `pallet_staking_incentive` using the recommended hardware.
pub struct Weights<T>(PhantomData<T>);
impl<T: sdk::frame_system::Config> WeightInfo for Weights<T> {
	/// Storage: `StakingIncentive::Fuse` (r:1 w:0)
	/// Proof: `StakingIncentive::Fuse` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `StakingIncentive::Global` (r:1 w:1)
	/// Proof: `StakingIncentive::Global` (`max_values`: Some(1), `max_size`: Some(68), added: 563, mode: `MaxEncodedLen`)
	/// Storage: `StakingIncentive::Payouts` (r:1 w:1)
	/// Proof: `StakingIncentive::Payouts` (`max_values`: Some(1), `max_size`: Some(833), added: 1328, mode: `MaxEncodedLen`)
	fn new_payout() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `238`
		//  Estimated: `2318`
		// Minimum execution time: 13_410_000 picoseconds.
		Weight::from_parts(13_910_000, 2318)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `StakingIncentive::Fuse` (r:0 w:1)
	/// Proof: `StakingIncentive::Fuse` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn reset_fuse() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_810_000 picoseconds.
		Weight::from_parts(5_280_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `StakingIncentive::Fuse` (r:1 w:0)
	/// Proof: `StakingIncentive::Fuse` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `StakingIncentive::Global` (r:1 w:1)
	/// Proof: `StakingIncentive::Global` (`max_values`: Some(1), `max_size`: Some(68), added: 563, mode: `MaxEncodedLen`)
	/// Storage: `StakingIncentive::Accounts` (r:1 w:1)
	/// Proof: `StakingIncentive::Accounts` (`max_values`: None, `max_size`: Some(101), added: 2576, mode: `MaxEncodedLen`)
	/// Storage: `StakingIncentive::Payouts` (r:1 w:0)
	/// Proof: `StakingIncentive::Payouts` (`max_values`: Some(1), `max_size`: Some(833), added: 1328, mode: `MaxEncodedLen`)
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: Some(345), added: 2820, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(697), added: 3172, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[0, 3]`.
	fn update_and_claim(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `328 + p * (172 ±0)`
		//  Estimated: `4162`
		// Minimum execution time: 16_710_000 picoseconds.
		Weight::from_parts(34_109_082, 4162)
			// Standard Error: 1_181_400
			.saturating_add(Weight::from_parts(57_069_926, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(p.into())))
	}
}
