
//! Autogenerated weights for `pallet_hold_vesting`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2024-11-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `wigy-ryzen`, CPU: `AMD Ryzen 7 5700G with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// target/release/mosaic-testnet-solo
// benchmark
// pallet
// --pallet
// pallet-hold-vesting
// --extrinsic
// *
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --output
// pallets/hold-vesting/src/weights.rs
// --template
// scripts/benchmark-pallet-weights.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_hold_vesting`.
pub trait WeightInfo {
	fn vest_locked(l: u32, s: u32, ) -> Weight;
	fn vest_unlocked(l: u32, s: u32, ) -> Weight;
	fn vest_other_locked(l: u32, s: u32, ) -> Weight;
	fn vest_other_unlocked(l: u32, s: u32, ) -> Weight;
	fn vested_transfer(l: u32, s: u32, ) -> Weight;
	fn force_vested_transfer(l: u32, s: u32, ) -> Weight;
	fn not_unlocking_merge_schedules(l: u32, s: u32, ) -> Weight;
	fn unlocking_merge_schedules(l: u32, s: u32, ) -> Weight;
	fn force_remove_vesting_schedule(l: u32, s: u32, ) -> Weight;
	fn start_vesting_schedule_unlocked(l: u32, s: u32, ) -> Weight;
	fn start_vesting_schedule_locked(l: u32, s: u32, ) -> Weight;
}

/// Weights for `pallet_hold_vesting` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: sdk::frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn vest_locked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 20_318_000 picoseconds.
		Weight::from_parts(21_446_882, 3892)
			// Standard Error: 8_905
			.saturating_add(Weight::from_parts(40_342, 0).saturating_mul(l.into()))
			// Standard Error: 5_438
			.saturating_add(Weight::from_parts(140_074, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn vest_unlocked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 48_040_000 picoseconds.
		Weight::from_parts(49_543_942, 3892)
			// Standard Error: 19_379
			.saturating_add(Weight::from_parts(340_355, 0).saturating_mul(l.into()))
			// Standard Error: 11_835
			.saturating_add(Weight::from_parts(206_156, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn vest_other_locked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 21_620_000 picoseconds.
		Weight::from_parts(22_420_675, 3892)
			// Standard Error: 9_830
			.saturating_add(Weight::from_parts(121_264, 0).saturating_mul(l.into()))
			// Standard Error: 6_003
			.saturating_add(Weight::from_parts(165_460, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn vest_other_unlocked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `349 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 52_659_000 picoseconds.
		Weight::from_parts(54_390_926, 3892)
			// Standard Error: 19_468
			.saturating_add(Weight::from_parts(320_925, 0).saturating_mul(l.into()))
			// Standard Error: 11_889
			.saturating_add(Weight::from_parts(193_126, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 7]`.
	fn vested_transfer(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `383 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 95_660_000 picoseconds.
		Weight::from_parts(100_313_323, 3892)
			// Standard Error: 30_716
			.saturating_add(Weight::from_parts(15_058, 0).saturating_mul(l.into()))
			// Standard Error: 21_321
			.saturating_add(Weight::from_parts(185_112, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 7]`.
	fn force_vested_transfer(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `486 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `6196 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 100_078_000 picoseconds.
		Weight::from_parts(102_987_071, 6196)
			// Standard Error: 30_733
			.saturating_add(Weight::from_parts(337_787, 0).saturating_mul(l.into()))
			// Standard Error: 21_333
			.saturating_add(Weight::from_parts(339_752, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[2, 8]`.
	fn not_unlocking_merge_schedules(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 22_653_000 picoseconds.
		Weight::from_parts(23_494_886, 3892)
			// Standard Error: 8_484
			.saturating_add(Weight::from_parts(76_949, 0).saturating_mul(l.into()))
			// Standard Error: 5_889
			.saturating_add(Weight::from_parts(161_661, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[2, 8]`.
	fn unlocking_merge_schedules(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `310 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 53_691_000 picoseconds.
		Weight::from_parts(56_023_464, 3892)
			// Standard Error: 18_255
			.saturating_add(Weight::from_parts(135_170, 0).saturating_mul(l.into()))
			// Standard Error: 12_671
			.saturating_add(Weight::from_parts(123_040, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[2, 8]`.
	fn force_remove_vesting_schedule(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `383 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 55_455_000 picoseconds.
		Weight::from_parts(57_929_198, 3892)
			// Standard Error: 16_496
			.saturating_add(Weight::from_parts(103_845, 0).saturating_mul(l.into()))
			// Standard Error: 11_450
			.saturating_add(Weight::from_parts(135_292, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn start_vesting_schedule_unlocked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `379 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 52_448_000 picoseconds.
		Weight::from_parts(53_766_303, 3892)
			// Standard Error: 18_705
			.saturating_add(Weight::from_parts(500_426, 0).saturating_mul(l.into()))
			// Standard Error: 11_423
			.saturating_add(Weight::from_parts(251_135, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn start_vesting_schedule_locked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `205 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 21_962_000 picoseconds.
		Weight::from_parts(22_674_349, 3892)
			// Standard Error: 7_098
			.saturating_add(Weight::from_parts(75_780, 0).saturating_mul(l.into()))
			// Standard Error: 4_335
			.saturating_add(Weight::from_parts(152_381, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn vest_locked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 20_318_000 picoseconds.
		Weight::from_parts(21_446_882, 3892)
			// Standard Error: 8_905
			.saturating_add(Weight::from_parts(40_342, 0).saturating_mul(l.into()))
			// Standard Error: 5_438
			.saturating_add(Weight::from_parts(140_074, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn vest_unlocked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 48_040_000 picoseconds.
		Weight::from_parts(49_543_942, 3892)
			// Standard Error: 19_379
			.saturating_add(Weight::from_parts(340_355, 0).saturating_mul(l.into()))
			// Standard Error: 11_835
			.saturating_add(Weight::from_parts(206_156, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn vest_other_locked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 21_620_000 picoseconds.
		Weight::from_parts(22_420_675, 3892)
			// Standard Error: 9_830
			.saturating_add(Weight::from_parts(121_264, 0).saturating_mul(l.into()))
			// Standard Error: 6_003
			.saturating_add(Weight::from_parts(165_460, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn vest_other_unlocked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `349 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 52_659_000 picoseconds.
		Weight::from_parts(54_390_926, 3892)
			// Standard Error: 19_468
			.saturating_add(Weight::from_parts(320_925, 0).saturating_mul(l.into()))
			// Standard Error: 11_889
			.saturating_add(Weight::from_parts(193_126, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 7]`.
	fn vested_transfer(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `383 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 95_660_000 picoseconds.
		Weight::from_parts(100_313_323, 3892)
			// Standard Error: 30_716
			.saturating_add(Weight::from_parts(15_058, 0).saturating_mul(l.into()))
			// Standard Error: 21_321
			.saturating_add(Weight::from_parts(185_112, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 7]`.
	fn force_vested_transfer(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `486 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `6196 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 100_078_000 picoseconds.
		Weight::from_parts(102_987_071, 6196)
			// Standard Error: 30_733
			.saturating_add(Weight::from_parts(337_787, 0).saturating_mul(l.into()))
			// Standard Error: 21_333
			.saturating_add(Weight::from_parts(339_752, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[2, 8]`.
	fn not_unlocking_merge_schedules(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 22_653_000 picoseconds.
		Weight::from_parts(23_494_886, 3892)
			// Standard Error: 8_484
			.saturating_add(Weight::from_parts(76_949, 0).saturating_mul(l.into()))
			// Standard Error: 5_889
			.saturating_add(Weight::from_parts(161_661, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[2, 8]`.
	fn unlocking_merge_schedules(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `310 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 53_691_000 picoseconds.
		Weight::from_parts(56_023_464, 3892)
			// Standard Error: 18_255
			.saturating_add(Weight::from_parts(135_170, 0).saturating_mul(l.into()))
			// Standard Error: 12_671
			.saturating_add(Weight::from_parts(123_040, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[2, 8]`.
	fn force_remove_vesting_schedule(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `383 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 55_455_000 picoseconds.
		Weight::from_parts(57_929_198, 3892)
			// Standard Error: 16_496
			.saturating_add(Weight::from_parts(103_845, 0).saturating_mul(l.into()))
			// Standard Error: 11_450
			.saturating_add(Weight::from_parts(135_292, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn start_vesting_schedule_unlocked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `379 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 52_448_000 picoseconds.
		Weight::from_parts(53_766_303, 3892)
			// Standard Error: 18_705
			.saturating_add(Weight::from_parts(500_426, 0).saturating_mul(l.into()))
			// Standard Error: 11_423
			.saturating_add(Weight::from_parts(251_135, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
	/// Storage: `HoldVesting::Vesting` (r:1 w:1)
	/// Proof: `HoldVesting::Vesting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 4]`.
	/// The range of component `s` is `[1, 8]`.
	fn start_vesting_schedule_locked(l: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `205 + l * (19 ±0) + s * (37 ±0)`
		//  Estimated: `3892 + l * (19 ±0) + s * (37 ±0)`
		// Minimum execution time: 21_962_000 picoseconds.
		Weight::from_parts(22_674_349, 3892)
			// Standard Error: 7_098
			.saturating_add(Weight::from_parts(75_780, 0).saturating_mul(l.into()))
			// Standard Error: 4_335
			.saturating_add(Weight::from_parts(152_381, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 19).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(s.into()))
	}
}
