//! # Permission NFT Pallet
//!
//! This pallet provides functionality for managing permission with NFTs.
//! Each NFT represents a permission associated with a specific nominal value.
//!
//! The pallet is built on top of the `pallet_nfts` pallet to manage the creation, ownership,
//! and attributes of the permission NFTs. The pallet allows users to mint new permission
//! NFTs, bond/unbond NFTs to/from their accounts, and chill/unchill NFTs to prevent/re-enable
//! their use.
//!
//! ## Overview
//!
//! `PermissionBondInterface`: A trait defining the interface for bonding, unbonding, chilling,
//! and unchilling permission NFTs. An empty implementation is provided as a fallback.
//! The pallet supports the following operations:
//!
//! - Minting a new permission NFT with a specific permission and nominal value.
//! - Bonding a permission NFT to an account, effectively locking its use.
//! - Unbonding a bonded permission NFT, releasing its use.
//! - Chilling a bonded permission NFT to temporarily disable its use.
//! - Unchilling a chilled permission NFT to re-enable its use.
//!
//! ## Configuration
//!
//! The pallet's behavior can be customized by implementing the `Config` trait. This trait defines
//! various associated types and constants required for the pallet's operation. Some key configuration
//! parameters include:
//!
//! - `RuntimeEvent`: Specifies the event type emitted by the pallet.
//! - `PalletId`: The ID of the pallet used to derive collection owner's addresses.
//! - `PrivilegedOrigin`: The origin authorized to mint tokens and modify them.
//! - `Balance`: The balance type used for nominal value and related calculations.
//! - `Permission`: The permission type stored among the token's attributes.
//! - `BondInterface`: Interface for managing bonding and unbonding of permission NFTs.
//! - `ItemIdSuccession`: The way the next item's ID is generated.
//! - `WeightInfo`: Type representing the weight of the pallet operations.

// clippy::pedantic warnings coming from code generated by macros that annoy the hell out of me
#![allow(
	clippy::must_use_candidate,
	clippy::cast_possible_truncation,
	dead_code,
	clippy::used_underscore_binding,
	clippy::wildcard_imports
)]
#![cfg_attr(not(feature = "std"), no_std)]

pub use pallet::*;

#[cfg(test)]
mod mock;

#[cfg(test)]
mod tests;

#[cfg(feature = "runtime-benchmarks")]
mod benchmarking;
pub mod weights;
pub use weights::*;

// TODO: Once the pallet is ready turn off dev_mode
#[frame_support::pallet(dev_mode)]
pub mod pallet {
	use sp_std::{
		collections::btree_map::{BTreeMap, Entry},
		vec::Vec,
	};

	use codec::Codec;

	use super::WeightInfo;
	use frame_support::{
		pallet_prelude::*,
		traits::{
			tokens::nonfungibles_v2::{Create, Inspect, Mutate, Transfer},
			BuildGenesisConfig,
		},
		PalletId,
	};
	use pallet_nfts::{
		CollectionConfig, CollectionSettings, Config as NftsConfig, ItemConfig, ItemSettings,
		MintSettings, MintType, Pallet as NftsPallet,
	};
	use sp_runtime::{traits::AccountIdConversion, BoundedVec, DispatchError, FixedPointOperand};

	use frame_system::pallet_prelude::OriginFor;

	use utils::traits::Successor;

	const PERMISSION_KEY: &[u8] = b"PERMISSION";
	const NOMINAL_VALUE_KEY: &[u8] = b"NOMINAL_VALUE";

	#[pallet::pallet]
	pub struct Pallet<T>(_);

	/// Configure the pallet by specifying the parameters and types on which it depends.
	#[pallet::config]
	pub trait Config: frame_system::Config + NftsConfig {
		/// Because this pallet emits events, it depends on the runtime's definition of an event.
		type RuntimeEvent: From<Event<Self>> + IsType<<Self as frame_system::Config>::RuntimeEvent>;

		/// The id of the pallet from witch the collection owner's address is derived.
		#[pallet::constant]
		type PalletId: Get<PalletId>;

		/// The origin that is authorized to mint new tokens and modify existing ones.
		type PrivilegedOrigin: EnsureOrigin<Self::RuntimeOrigin>;

		/// Used for the nominal value of permission tokens
		type Balance: Parameter
			+ Member
			+ sp_runtime::traits::AtLeast32BitUnsigned
			+ Codec
			+ Default
			+ Copy
			+ MaybeSerializeDeserialize
			+ MaxEncodedLen
			+ TypeInfo
			+ FixedPointOperand;

		/// The permission type that is stored amongst the token's attributes.
		type Permission: Parameter + Member + Codec + MaybeSerializeDeserialize;

		/// A way the next item's id is generated.
		type ItemIdSuccession: Successor<Self::ItemId>;

		/// Type representing the weight of this pallet
		type WeightInfo: WeightInfo;
	}

	/// The id of the collection that's managed by this pallet.
	#[pallet::storage]
	#[pallet::getter(fn collection_id)]
	pub type CollectionId<T: Config> = StorageValue<_, <T as NftsConfig>::CollectionId>;

	/// The account who owns the managed collection. Derived from the `PalletId`.
	#[pallet::storage]
	#[pallet::getter(fn pallet_account_id)]
	pub type PalletAccountId<T: Config> = StorageValue<_, T::AccountId>;

	#[pallet::storage]
	#[pallet::getter(fn next_item_id)]
	pub type NextItemId<T: Config> = StorageValue<_, <T as NftsConfig>::ItemId>;

	#[pallet::storage]
	pub type BondedTokens<T: Config> =
		StorageValue<_, BTreeMap<T::AccountId, (<T as NftsConfig>::ItemId, bool)>>;

	#[pallet::event]
	#[pallet::generate_deposit(pub(super) fn deposit_event)]
	pub enum Event<T: Config> {
		/// A token has been minted to the specified account.
		TokenCreated { account: T::AccountId, item_id: <T as NftsConfig>::ItemId },
		/// A token's suspend status has been modified.
		TokenSuspendSet { item_id: <T as NftsConfig>::ItemId, suspended: bool },
		/// A token has been successfully bonded
		TokenBonded { item_id: <T as NftsConfig>::ItemId },
		/// A token has been successfully unbonded
		TokenUnbonded { item_id: <T as NftsConfig>::ItemId },
		/// A token has been successfully chilled
		TokenChilled { item_id: <T as NftsConfig>::ItemId },
		/// A token has been successfully unchilled
		TokenUnchilled { item_id: <T as NftsConfig>::ItemId },
	}

	#[pallet::error]
	pub enum Error<T> {
		NotInitialized,
		WrongOwner,
		AlreadyBonded,
		NotBonded,
		AlreadyChilled,
		NotChilled,
	}

	#[pallet::genesis_config]
	pub struct GenesisConfig<T: Config> {
		pub initial_permission_holders: Vec<(T::AccountId, T::Permission, bool, T::Balance)>,
	}

	impl<T: Config> Default for GenesisConfig<T> {
		fn default() -> Self {
			Self { initial_permission_holders: Vec::new() }
		}
	}

	#[pallet::genesis_build]
	impl<T: Config> BuildGenesisConfig for GenesisConfig<T> {
		fn build(&self) {
			let admin: T::AccountId = T::PalletId::get().into_account_truncating();
			PalletAccountId::<T>::put(admin.clone());

			let collection_id = NftsPallet::<T>::create_collection(
				&admin,
				&admin,
				&CollectionConfig {
					settings: CollectionSettings::default(),
					max_supply: None,
					mint_settings: MintSettings {
						mint_type: MintType::Issuer,
						price: None,
						start_block: None,
						end_block: None,
						default_item_settings: ItemSettings::default(),
					},
				},
			)
			.expect("could create collection");

			CollectionId::<T>::put(collection_id);
			let mut bonded_tokens =
				BTreeMap::<T::AccountId, (<T as NftsConfig>::ItemId, bool)>::new();

			let mut item_id = T::ItemIdSuccession::initial();
			for (account_id, permission, bonded, nominal_value) in &self.initial_permission_holders
			{
				NftsPallet::<T>::mint_into(
					&collection_id,
					&item_id,
					account_id,
					&ItemConfig::default(),
					true,
				)
				.expect("could mint new permission nft");

				nominal_value
					.using_encoded(|nominal_value| {
						permission.using_encoded(|permission| {
							Pallet::<T>::init_attributes(
								&collection_id,
								&item_id,
								permission,
								nominal_value,
							)
						})
					})
					.expect("could initialize attributes");

				item_id = T::ItemIdSuccession::successor(&item_id);

				if *bonded {
					<NftsPallet<T> as Transfer<_>>::disable_transfer(&collection_id, &item_id)
						.expect("could disable transfer");
					bonded_tokens.insert(account_id.clone(), (item_id, false));
				}
			}

			NextItemId::<T>::put(item_id);
			BondedTokens::<T>::put(bonded_tokens);
		}
	}

	impl<T: Config> Pallet<T> {
		/// Bond a permission NFT to an account, locking its use.
		///
		/// # Errors
		///
		/// - Pallet is not initialized.
		/// - Origin is not authorized.
		/// - NFT is not owned by caller.
		/// - An NFT is already bonded.
		pub fn do_bond(
			account_id: &T::AccountId,
			item_id: &<T as NftsConfig>::ItemId,
		) -> Result<(T::Permission, T::Balance), DispatchError> {
			let collection_id = Self::collection_id().ok_or(Error::<T>::NotInitialized)?;

			ensure!(
				NftsPallet::<T>::owner(collection_id, *item_id)
					.is_some_and(|owner| owner == *account_id),
				Error::<T>::WrongOwner
			);

			let mut bonded_tokens = BondedTokens::<T>::get().ok_or(Error::<T>::NotInitialized)?;

			if let Entry::Vacant(c) = bonded_tokens.entry(account_id.clone()) {
				c.insert((*item_id, false));

				<NftsPallet<T> as Transfer<_>>::disable_transfer(&collection_id, item_id)?;

				let permission = Self::get_permission(&collection_id, item_id)?;
				let nominal_value = Self::get_nominal_value(&collection_id, item_id)?;

				BondedTokens::<T>::put(bonded_tokens);
				Self::deposit_event(Event::<T>::TokenBonded { item_id: *item_id });

				Ok((permission, nominal_value))
			} else {
				Err(Error::<T>::AlreadyBonded.into())
			}
		}

		/// Unbond a bonded permission NFT, releasing its use.
		///
		/// # Errors
		///
		/// - Pallet is not initialized.
		/// - NFT is not chilled.
		pub fn do_unbond(
			account_id: &T::AccountId,
			new_nominal_value: &T::Balance,
		) -> DispatchResult {
			let mut bonded_tokens = BondedTokens::<T>::get().ok_or(Error::<T>::NotInitialized)?;

			if let Entry::Occupied(entry) = bonded_tokens.entry(account_id.clone()) {
				if !entry.get().1 {
					return Err(Error::<T>::NotChilled.into());
				}
				let (_account_id, (item_id, _chilled)) = entry.remove_entry();

				let collection_id = Self::collection_id().ok_or(Error::<T>::NotInitialized)?;

				new_nominal_value.using_encoded(|nominal_value| {
					<NftsPallet<T> as Mutate<_, _>>::set_attribute(
						&collection_id,
						&item_id,
						NOMINAL_VALUE_KEY,
						nominal_value,
					)
				})?;

				<NftsPallet<T> as Transfer<_>>::enable_transfer(&collection_id, &item_id)?;

				BondedTokens::<T>::put(bonded_tokens);
				Self::deposit_event(Event::<T>::TokenUnbonded { item_id });

				Ok(())
			} else {
				Err(Error::<T>::NotBonded.into())
			}
		}

		/// Temporarily chill a bonded permission NFT, disabling its use.
		///
		/// # Errors
		///
		/// - Pallet is not initialized.
		/// - NFT is not bonded.
		/// - NFT is already chilled.
		pub fn do_chill(account_id: &T::AccountId) -> DispatchResult {
			let mut bonded_tokens = BondedTokens::<T>::get().ok_or(Error::<T>::NotInitialized)?;

			if let Entry::Occupied(mut c) = bonded_tokens.entry(account_id.clone()) {
				if c.get().1 {
					return Err(Error::<T>::AlreadyChilled.into());
				}

				let (item_id, chilled) = c.get_mut();
				*chilled = true;

				Self::deposit_event(Event::<T>::TokenChilled { item_id: *item_id });
				BondedTokens::<T>::put(bonded_tokens);

				Ok(())
			} else {
				Err(Error::<T>::NotBonded.into())
			}
		}

		/// Unchill a chilled permission NFT, re-enabling its use.
		///
		/// # Errors
		///
		/// - Pallet is not initialized.
		/// - NFT is not bonded.
		/// - NFT is not chilled.
		pub fn do_unchill(account_id: &T::AccountId) -> DispatchResult {
			let mut bonded_tokens = BondedTokens::<T>::get().ok_or(Error::<T>::NotInitialized)?;

			if let Entry::Occupied(mut c) = bonded_tokens.entry(account_id.clone()) {
				if !(c.get().1) {
					return Err(Error::<T>::NotChilled.into());
				}

				let (item_id, chilled) = c.get_mut();
				*chilled = false;

				Self::deposit_event(Event::<T>::TokenUnchilled { item_id: *item_id });
				BondedTokens::<T>::put(bonded_tokens);

				Ok(())
			} else {
				Err(Error::<T>::NotBonded.into())
			}
		}

		/// Returns an iterator over account ids
		pub fn accounts_with_bonded_permission(
		) -> Result<impl Iterator<Item = T::AccountId>, DispatchError> {
			let bonded_tokens = BondedTokens::<T>::get().ok_or(Error::<T>::NotInitialized)?;
			Ok(bonded_tokens
				.into_iter()
				.filter_map(|(account_id, (_, chilled))| (!chilled).then_some(account_id)))
		}

		/// Mint a new permission NFT with provided permission and nominal value.
		///
		/// # Parameters
		///
		/// - `account_id`: Account to assign the NFT.
		/// - `permission`: Permission associated with the NFT.
		/// - `nominal_value`: Nominal value of the NFT.
		///
		/// # Errors
		///
		/// - Pallet is not initialized.
		/// - Error during minting process.
		pub fn do_mint_permission_token(
			account_id: &T::AccountId,
			permission: &T::Permission,
			nominal_value: &T::Balance,
		) -> Result<<T as NftsConfig>::ItemId, DispatchError> {
			nominal_value.using_encoded(|nominal_value| {
				permission.using_encoded(|permission| {
					Self::create_token(account_id, permission, nominal_value)
				})
			})
		}

		fn get_nominal_value(
			collection_id: &<T as NftsConfig>::CollectionId,
			item_id: &<T as NftsConfig>::ItemId,
		) -> Result<T::Balance, DispatchError> {
			T::Balance::decode(
				&mut NftsPallet::<T>::system_attribute(collection_id, item_id, NOMINAL_VALUE_KEY)
					.ok_or(Error::<T>::NotInitialized)?
					.as_slice(),
			)
			.map_err(|_| Error::<T>::NotInitialized.into())
		}

		fn get_permission(
			collection_id: &<T as NftsConfig>::CollectionId,
			item_id: &<T as NftsConfig>::ItemId,
		) -> Result<T::Permission, DispatchError> {
			T::Permission::decode(
				&mut NftsPallet::<T>::system_attribute(collection_id, item_id, PERMISSION_KEY)
					.ok_or(Error::<T>::NotInitialized)?
					.as_slice(),
			)
			.map_err(|_| Error::<T>::NotInitialized.into())
		}

		fn init_attributes(
			collection_id: &<T as NftsConfig>::CollectionId,
			item_id: &<T as NftsConfig>::ItemId,
			permission: &[u8],
			nominal_value: &[u8],
		) -> DispatchResult {
			<NftsPallet<T> as Mutate<_, _>>::set_attribute(
				collection_id,
				item_id,
				PERMISSION_KEY,
				permission,
			)?;

			<NftsPallet<T> as Mutate<_, _>>::set_attribute(
				collection_id,
				item_id,
				NOMINAL_VALUE_KEY,
				nominal_value,
			)
		}

		fn create_token(
			account_id: &T::AccountId,
			permission: &[u8],
			nominal_value: &[u8],
		) -> Result<<T as NftsConfig>::ItemId, DispatchError> {
			let item_id = Self::next_item_id().ok_or(Error::<T>::NotInitialized)?;
			let collection_id = Self::collection_id().ok_or(Error::<T>::NotInitialized)?;

			NftsPallet::<T>::mint_into(
				&collection_id,
				&item_id,
				account_id,
				&ItemConfig::default(),
				true,
			)?;

			Self::init_attributes(&collection_id, &item_id, permission, nominal_value)?;

			Pallet::<T>::deposit_event(Event::<T>::TokenCreated {
				account: account_id.clone(),
				item_id,
			});

			NextItemId::<T>::put(T::ItemIdSuccession::successor(&item_id));

			Ok(item_id)
		}
	}

	// TODO: calculate weights
	#[pallet::call]
	impl<T: Config> Pallet<T> {
		/// Mint a new permission NFT with provided permission and nominal value.
		///
		/// # Parameters
		///
		/// - `origin`: Caller's origin.
		/// - `account_id`: Account to assign the NFT.
		/// - `permission`: Permission associated with the NFT.
		/// - `nominal_value`: Nominal value of the NFT.
		///
		/// # Errors
		///
		/// - Pallet is not initialized.
		/// - Origin is not authorized.
		/// - Error during minting process.
		#[pallet::call_index(0)]
		pub fn mint_permission_token(
			origin: OriginFor<T>,
			account_id: T::AccountId,
			permission: BoundedVec<u8, <T as NftsConfig>::ValueLimit>,
			nominal_value: BoundedVec<u8, <T as NftsConfig>::ValueLimit>,
		) -> DispatchResult {
			T::PrivilegedOrigin::ensure_origin(origin)?;
			Self::create_token(&account_id, permission.as_slice(), nominal_value.as_slice())
				.map(|_| ())
		}
	}
}
