//TODO: Rewrite docs
//! # NFT permission pallet
//! This module makes it possible to use NFTs as permission tokens.
//! It allows you to define and manage permissions for accounts
//! by minting NFTs representing different permissions and then checking
//! these NFTs to determine if an account has a particular permission.
//!
//! Additionally, the pallet provides functionality to suspend or unsuspend permission NFTs
//! to temporarily revoke or restore permissions for specific accounts.
//!
//! The pallet is built on top of `pallet_nfts`, which handles the underlying NFT functionality.
//!
//! ## Overview
//!
//! The NFT permission pallet provides the following features:
//!
//! - **Minting permission NFTs:** The pallet allows privileged accounts
//!   to mint new permission NFTs associated with a specific permission.
//!   These NFTs are owned by accounts and represent their permissions.
//!
//! - **Checking permissions:** The pallet provides functions to check if an account
//!   has a specific permission by inspecting their owned permission NFTs.
//!   Suspended NFTs are not considered when checking permissions.
//!
//! - **Suspending permission NFTs:** Privileged accounts can suspend a specific permission NFT,
//!   temporarily revoking the associated permission for the account that owns it.
//!
//! - **Suspending all permission NFTs for an account:** Privileged accounts can suspend all
//!   permission NFTs associated with a particular permission for a given user account.
//!
//! ## Genesis Configuration
//!
//! The pallet requires an initial configuration during genesis,
//! which includes setting the privileged accounts and their associated permissions.

// clippy::pedantic warnings coming from code generated by macros that annoy the hell out of me
#![allow(
	clippy::must_use_candidate,
	clippy::cast_possible_truncation,
	dead_code,
	clippy::used_underscore_binding,
	clippy::wildcard_imports
)]
#![cfg_attr(not(feature = "std"), no_std)]

pub use pallet::*;

#[cfg(test)]
mod mock;

#[cfg(test)]
mod tests;

#[cfg(feature = "runtime-benchmarks")]
mod benchmarking;
pub mod weights;
pub use weights::*;

// TODO: Once the pallet is ready turn off dev_mode
#[frame_support::pallet(dev_mode)]
pub mod pallet {
	use sp_std::{
		collections::btree_map::{BTreeMap, Entry},
		vec::Vec,
	};

	use codec::Codec;

	use super::WeightInfo;
	use frame_support::{
		pallet_prelude::*,
		traits::{
			tokens::nonfungibles_v2::{Create, Inspect, Mutate, Transfer},
			BuildGenesisConfig,
		},
		PalletId,
	};
	use pallet_nfts::{
		CollectionConfig, CollectionSettings, Config as NftsConfig, ItemConfig, ItemSettings,
		MintSettings, MintType, Pallet as NftsPallet,
	};
	use sp_runtime::{traits::AccountIdConversion, BoundedVec, DispatchError, FixedPointOperand};

	use frame_system::{ensure_signed, pallet_prelude::OriginFor};

	use utils::traits::Successor;

	pub trait PermissionBondInterface<AccountId, Permission, Balance> {
		fn bond(
			account_id: AccountId,
			permission: Permission,
			nominal_value: Balance,
		) -> DispatchResult;
		fn unbond(
			account_id: AccountId,
			permission: Permission,
			nominal_value: Balance,
		) -> Result<Balance, DispatchError>;
		fn chill(
			account_id: AccountId,
			permission: Permission,
			nominal_value: Balance,
		) -> DispatchResult;
		fn unchill(
			account_id: AccountId,
			permission: Permission,
			nominal_value: Balance,
		) -> DispatchResult;
	}

	impl<AccountId, Permission, Balance> PermissionBondInterface<AccountId, Permission, Balance>
		for ()
	{
		fn bond(_: AccountId, _: Permission, _: Balance) -> DispatchResult {
			Ok(())
		}
		fn unbond(
			_: AccountId,
			_: Permission,
			nominal_value: Balance,
		) -> Result<Balance, DispatchError> {
			Ok(nominal_value)
		}
		fn chill(_: AccountId, _: Permission, _: Balance) -> DispatchResult {
			Ok(())
		}
		fn unchill(_: AccountId, _: Permission, _: Balance) -> DispatchResult {
			Ok(())
		}
	}

	const PERMISSION_KEY: &[u8] = b"PERMISSION";
	const NOMINAL_VALUE_KEY: &[u8] = b"NOMINAL_VALUE";

	#[pallet::pallet]
	pub struct Pallet<T>(_);

	/// Configure the pallet by specifying the parameters and types on which it depends.
	#[pallet::config]
	pub trait Config: frame_system::Config + NftsConfig {
		/// Because this pallet emits events, it depends on the runtime's definition of an event.
		type RuntimeEvent: From<Event<Self>> + IsType<<Self as frame_system::Config>::RuntimeEvent>;

		/// The id of the pallet from witch the collection owner's address is derived.
		#[pallet::constant]
		type PalletId: Get<PalletId>;

		/// The origin that is authorized to mint new tokens and modify existing ones.
		type PrivilegedOrigin: EnsureOrigin<Self::RuntimeOrigin>;

		/// Used for the nominal value of permission tokens
		type Balance: Parameter
			+ Member
			+ sp_runtime::traits::AtLeast32BitUnsigned
			+ Codec
			+ Default
			+ Copy
			+ MaybeSerializeDeserialize
			+ MaxEncodedLen
			+ TypeInfo
			+ FixedPointOperand;

		/// The permission type that is stored amongst the token's attributes.
		type Permission: Parameter + Member + Codec + MaybeSerializeDeserialize;

		/// Interface through which tokens can be bound
		type BondInterface: PermissionBondInterface<
			Self::AccountId,
			Self::Permission,
			Self::Balance,
		>;

		/// A way the next item's id is generated.
		type ItemIdSuccession: Successor<Self::ItemId>;

		/// Type representing the weight of this pallet
		type WeightInfo: WeightInfo;
	}

	/// The id of the collection that's managed by this pallet.
	#[pallet::storage]
	#[pallet::getter(fn collection_id)]
	pub type CollectionId<T: Config> = StorageValue<_, <T as NftsConfig>::CollectionId>;

	/// The account who owns the managed collection. Derived from the `PalletId`.
	#[pallet::storage]
	#[pallet::getter(fn pallet_account_id)]
	pub type PalletAccountId<T: Config> = StorageValue<_, T::AccountId>;

	#[pallet::storage]
	#[pallet::getter(fn next_item_id)]
	pub type NextItemId<T: Config> = StorageValue<_, <T as NftsConfig>::ItemId>;

	#[pallet::storage]
	pub type BondedTokens<T: Config> =
		StorageValue<_, BTreeMap<T::AccountId, (<T as NftsConfig>::ItemId, bool)>>;

	#[pallet::event]
	#[pallet::generate_deposit(pub(super) fn deposit_event)]
	pub enum Event<T: Config> {
		/// A token has been minted to the specified account.
		TokenCreated { account: T::AccountId, item_id: <T as NftsConfig>::ItemId },
		/// A token's suspend status has been modified.
		TokenSuspendSet { item_id: <T as NftsConfig>::ItemId, suspended: bool },
		/// A token has been successfully bonded
		TokenBonded { item_id: <T as NftsConfig>::ItemId },
		/// A token has been successfully unbonded
		TokenUnbonded { item_id: <T as NftsConfig>::ItemId },
		/// A token has been successfully chilled
		TokenChilled { item_id: <T as NftsConfig>::ItemId },
		/// A token has been successfully unchilled
		TokenUnchilled { item_id: <T as NftsConfig>::ItemId },
	}

	#[pallet::error]
	pub enum Error<T> {
		NotInitialized,
		WrongOwner,
		AlreadyBonded,
		NotBonded,
		AlreadyChilled,
		NotChilled,
	}

	#[pallet::genesis_config]
	pub struct GenesisConfig<T: Config> {
		pub initial_permission_holders: Vec<(T::AccountId, T::Permission, bool, T::Balance)>,
	}

	impl<T: Config> Default for GenesisConfig<T> {
		fn default() -> Self {
			Self { initial_permission_holders: Vec::new() }
		}
	}

	#[pallet::genesis_build]
	impl<T: Config> BuildGenesisConfig for GenesisConfig<T> {
		fn build(&self) {
			let admin: T::AccountId = T::PalletId::get().into_account_truncating();
			PalletAccountId::<T>::put(admin.clone());

			let collection_id = NftsPallet::<T>::create_collection(
				&admin,
				&admin,
				&CollectionConfig {
					settings: CollectionSettings::default(),
					max_supply: None,
					mint_settings: MintSettings {
						mint_type: MintType::Issuer,
						price: None,
						start_block: None,
						end_block: None,
						default_item_settings: ItemSettings::default(),
					},
				},
			)
			.expect("could create collection");

			CollectionId::<T>::put(collection_id);
			let mut bonded_tokens =
				BTreeMap::<T::AccountId, (<T as NftsConfig>::ItemId, bool)>::new();

			let mut item_id = T::ItemIdSuccession::initial();
			for (account_id, permission, bonded, nominal_value) in &self.initial_permission_holders
			{
				NftsPallet::<T>::mint_into(
					&collection_id,
					&item_id,
					account_id,
					&ItemConfig::default(),
					true,
				)
				.expect("could mint new permission nft");

				nominal_value
					.using_encoded(|nominal_value| {
						permission.using_encoded(|permission| {
							Pallet::<T>::init_attributes(
								&collection_id,
								&item_id,
								permission,
								nominal_value,
							)
						})
					})
					.expect("could initialize attributes");

				item_id = T::ItemIdSuccession::successor(&item_id);

				if *bonded {
					<NftsPallet<T> as Transfer<_>>::disable_transfer(&collection_id, &item_id)
						.expect("could disable transfer");
					T::BondInterface::bond(account_id.clone(), permission.clone(), *nominal_value)
						.expect("could bond");
					bonded_tokens.insert(account_id.clone(), (item_id, false));
				}
			}

			NextItemId::<T>::put(item_id);
			BondedTokens::<T>::put(bonded_tokens);
		}
	}

	impl<T: Config> Pallet<T> {
		pub fn do_bond(
			account_id: &T::AccountId,
			item_id: &<T as NftsConfig>::ItemId,
		) -> DispatchResult {
			let collection_id = Self::collection_id().ok_or(Error::<T>::NotInitialized)?;

			ensure!(
				NftsPallet::<T>::owner(collection_id, *item_id)
					.is_some_and(|owner| owner == *account_id),
				Error::<T>::WrongOwner
			);

			let mut bonded_tokens = BondedTokens::<T>::get().ok_or(Error::<T>::NotInitialized)?;

			if let Entry::Vacant(c) = bonded_tokens.entry(account_id.clone()) {
				c.insert((*item_id, false));

				<NftsPallet<T> as Transfer<_>>::disable_transfer(&collection_id, item_id)?;

				let permission = Self::get_permission(&collection_id, item_id)?;
				let nominal_value = Self::get_nominal_value(&collection_id, item_id)?;
				T::BondInterface::bond(account_id.clone(), permission, nominal_value)?;

				BondedTokens::<T>::put(bonded_tokens);
				Self::deposit_event(Event::<T>::TokenBonded { item_id: *item_id });

				Ok(())
			} else {
				Err(Error::<T>::AlreadyBonded.into())
			}
		}

		pub fn do_unbond(account_id: &T::AccountId) -> DispatchResult {
			let mut bonded_tokens = BondedTokens::<T>::get().ok_or(Error::<T>::NotInitialized)?;

			if let Entry::Occupied(entry) = bonded_tokens.entry(account_id.clone()) {
				if !entry.get().1 {
					return Err(Error::<T>::NotChilled.into());
				}
				let (_account_id, (item_id, _chilled)) = entry.remove_entry();

				let collection_id = Self::collection_id().ok_or(Error::<T>::NotInitialized)?;

				let old_nominal_value = Self::get_nominal_value(&collection_id, &item_id)?;
				let permission = Self::get_permission(&collection_id, &item_id)?;

				let new_nominal_value =
					T::BondInterface::unbond(account_id.clone(), permission, old_nominal_value)?;

				new_nominal_value.using_encoded(|nominal_value| {
					<NftsPallet<T> as Mutate<_, _>>::set_attribute(
						&collection_id,
						&item_id,
						NOMINAL_VALUE_KEY,
						nominal_value,
					)
				})?;

				<NftsPallet<T> as Transfer<_>>::enable_transfer(&collection_id, &item_id)?;

				BondedTokens::<T>::put(bonded_tokens);
				Self::deposit_event(Event::<T>::TokenUnbonded { item_id });

				Ok(())
			} else {
				Err(Error::<T>::NotBonded.into())
			}
		}

		pub fn do_chill(account_id: &T::AccountId) -> DispatchResult {
			let mut bonded_tokens = BondedTokens::<T>::get().ok_or(Error::<T>::NotInitialized)?;

			if let Entry::Occupied(mut c) = bonded_tokens.entry(account_id.clone()) {
				if c.get().1 {
					return Err(Error::<T>::AlreadyChilled.into());
				}

				let (item_id, chilled) = c.get_mut();
				*chilled = true;

				let collection_id = Self::collection_id().ok_or(Error::<T>::NotInitialized)?;

				let nominal_value = Self::get_nominal_value(&collection_id, item_id)?;
				let permission = Self::get_permission(&collection_id, item_id)?;

				T::BondInterface::chill(account_id.clone(), permission, nominal_value)?;

				Self::deposit_event(Event::<T>::TokenChilled { item_id: *item_id });
				BondedTokens::<T>::put(bonded_tokens);

				Ok(())
			} else {
				Err(Error::<T>::NotBonded.into())
			}
		}

		pub fn do_unchill(account_id: &T::AccountId) -> DispatchResult {
			let mut bonded_tokens = BondedTokens::<T>::get().ok_or(Error::<T>::NotInitialized)?;

			if let Entry::Occupied(mut c) = bonded_tokens.entry(account_id.clone()) {
				if !(c.get().1) {
					return Err(Error::<T>::NotChilled.into());
				}

				let (item_id, chilled) = c.get_mut();
				*chilled = false;

				let collection_id = Self::collection_id().ok_or(Error::<T>::NotInitialized)?;

				let nominal_value = Self::get_nominal_value(&collection_id, item_id)?;
				let permission = Self::get_permission(&collection_id, item_id)?;

				T::BondInterface::unchill(account_id.clone(), permission, nominal_value)?;

				Self::deposit_event(Event::<T>::TokenUnchilled { item_id: *item_id });
				BondedTokens::<T>::put(bonded_tokens);

				Ok(())
			} else {
				Err(Error::<T>::NotBonded.into())
			}
		}

		/// Returns an iterator over account ids
		pub fn accounts_with_bonded_permission(
		) -> Result<impl Iterator<Item = T::AccountId>, DispatchError> {
			let bonded_tokens = BondedTokens::<T>::get().ok_or(Error::<T>::NotInitialized)?;
			Ok(bonded_tokens
				.into_iter()
				.filter_map(|(account_id, (_, chilled))| (!chilled).then_some(account_id)))
		}

		/// Mint a new permission NFT to an account with the provided permission.
		///
		/// # Errors
		///
		/// This function will return an error if the pallet has not yet been initialized
		/// or an error occurs within pallet_nfts
		pub fn do_mint_permission_token(
			account_id: &T::AccountId,
			permission: &T::Permission,
			nominal_value: &T::Balance,
		) -> Result<<T as NftsConfig>::ItemId, DispatchError> {
			nominal_value.using_encoded(|nominal_value| {
				permission.using_encoded(|permission| {
					Self::create_token(account_id, permission, nominal_value)
				})
			})
		}

		fn get_nominal_value(
			collection_id: &<T as NftsConfig>::CollectionId,
			item_id: &<T as NftsConfig>::ItemId,
		) -> Result<T::Balance, DispatchError> {
			T::Balance::decode(
				&mut NftsPallet::<T>::system_attribute(collection_id, item_id, NOMINAL_VALUE_KEY)
					.ok_or(Error::<T>::NotInitialized)?
					.as_slice(),
			)
			.map_err(|_| Error::<T>::NotInitialized.into())
		}

		fn get_permission(
			collection_id: &<T as NftsConfig>::CollectionId,
			item_id: &<T as NftsConfig>::ItemId,
		) -> Result<T::Permission, DispatchError> {
			T::Permission::decode(
				&mut NftsPallet::<T>::system_attribute(collection_id, item_id, PERMISSION_KEY)
					.ok_or(Error::<T>::NotInitialized)?
					.as_slice(),
			)
			.map_err(|_| Error::<T>::NotInitialized.into())
		}

		fn init_attributes(
			collection_id: &<T as NftsConfig>::CollectionId,
			item_id: &<T as NftsConfig>::ItemId,
			permission: &[u8],
			nominal_value: &[u8],
		) -> DispatchResult {
			<NftsPallet<T> as Mutate<_, _>>::set_attribute(
				collection_id,
				item_id,
				PERMISSION_KEY,
				permission,
			)?;

			<NftsPallet<T> as Mutate<_, _>>::set_attribute(
				collection_id,
				item_id,
				NOMINAL_VALUE_KEY,
				nominal_value,
			)
		}

		fn create_token(
			account_id: &T::AccountId,
			permission: &[u8],
			nominal_value: &[u8],
		) -> Result<<T as NftsConfig>::ItemId, DispatchError> {
			let item_id = Self::next_item_id().ok_or(Error::<T>::NotInitialized)?;
			let collection_id = Self::collection_id().ok_or(Error::<T>::NotInitialized)?;

			NftsPallet::<T>::mint_into(
				&collection_id,
				&item_id,
				account_id,
				&ItemConfig::default(),
				true,
			)?;

			Self::init_attributes(&collection_id, &item_id, permission, nominal_value)?;

			Pallet::<T>::deposit_event(Event::<T>::TokenCreated {
				account: account_id.clone(),
				item_id,
			});

			NextItemId::<T>::put(T::ItemIdSuccession::successor(&item_id));

			Ok(item_id)
		}
	}

	// TODO: calculate weights
	#[pallet::call]
	impl<T: Config> Pallet<T> {
		/// Mint a new permission NFT to an account with the provided permission.
		///
		/// # Errors
		///
		/// This function will return an error if the pallet has not yet been initialized,
		/// an error occurs within pallet_nfts or the origin isn't the privileged one.
		#[pallet::call_index(0)]
		pub fn mint_permission_token(
			origin: OriginFor<T>,
			account_id: T::AccountId,
			permission: BoundedVec<u8, <T as NftsConfig>::ValueLimit>,
			nominal_value: BoundedVec<u8, <T as NftsConfig>::ValueLimit>,
		) -> DispatchResult {
			T::PrivilegedOrigin::ensure_origin(origin)?;
			Self::create_token(&account_id, permission.as_slice(), nominal_value.as_slice())
				.map(|_| ())
		}

		#[pallet::call_index(1)]
		pub fn bond(origin: OriginFor<T>, item_id: <T as NftsConfig>::ItemId) -> DispatchResult {
			let account_id = ensure_signed(origin)?;
			Self::do_bond(&account_id, &item_id)
		}

		#[pallet::call_index(2)]
		pub fn unbond(origin: OriginFor<T>) -> DispatchResult {
			let account_id = ensure_signed(origin)?;
			Self::do_unbond(&account_id)
		}

		#[pallet::call_index(3)]
		pub fn chill(origin: OriginFor<T>) -> DispatchResult {
			let account_id = ensure_signed(origin)?;
			Self::do_chill(&account_id)
		}

		#[pallet::call_index(4)]
		pub fn unchill(origin: OriginFor<T>) -> DispatchResult {
			let account_id = ensure_signed(origin)?;
			Self::do_unchill(&account_id)
		}
	}
}
