
//! Autogenerated weights for `pallet_im_online`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2024-11-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `vismate-desktop`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// target/release/mosaic-testnet-solo
// benchmark
// pallet
// --pallet
// pallet-im-online
// --extrinsic
// *
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --output
// pallets/im-online/src/weights.rs
// --template
// scripts/benchmark-pallet-weights.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_im_online`.
pub trait WeightInfo {
	fn validate_unsigned_and_then_heartbeat(k: u32, ) -> Weight;
}

/// Weights for `pallet_im_online` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: sdk::frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ImOnline::Keys` (r:1 w:0)
	/// Proof: `ImOnline::Keys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ImOnline::ReceivedHeartbeats` (r:1 w:1)
	/// Proof: `ImOnline::ReceivedHeartbeats` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ImOnline::AuthoredBlocks` (r:1 w:0)
	/// Proof: `ImOnline::AuthoredBlocks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ValidatorSubsetSelection::AvgSessionLength` (r:1 w:0)
	/// Proof: `ValidatorSubsetSelection::AvgSessionLength` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `k` is `[1, 100]`.
	fn validate_unsigned_and_then_heartbeat(k: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1213 + k * (3 ±0)`
		//  Estimated: `4657 + k * (4 ±0)`
		// Minimum execution time: 56_769_000 picoseconds.
		Weight::from_parts(58_226_722, 4657)
			// Standard Error: 823
			.saturating_add(Weight::from_parts(50_821, 0).saturating_mul(k.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 4).saturating_mul(k.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `ImOnline::Keys` (r:1 w:0)
	/// Proof: `ImOnline::Keys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ImOnline::ReceivedHeartbeats` (r:1 w:1)
	/// Proof: `ImOnline::ReceivedHeartbeats` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ImOnline::AuthoredBlocks` (r:1 w:0)
	/// Proof: `ImOnline::AuthoredBlocks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ValidatorSubsetSelection::AvgSessionLength` (r:1 w:0)
	/// Proof: `ValidatorSubsetSelection::AvgSessionLength` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `k` is `[1, 100]`.
	fn validate_unsigned_and_then_heartbeat(k: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1213 + k * (3 ±0)`
		//  Estimated: `4657 + k * (4 ±0)`
		// Minimum execution time: 56_769_000 picoseconds.
		Weight::from_parts(58_226_722, 4657)
			// Standard Error: 823
			.saturating_add(Weight::from_parts(50_821, 0).saturating_mul(k.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 4).saturating_mul(k.into()))
	}
}
