#[path = "../../../../parachain/src/weights/pallet/airdrop.rs"]
pub mod airdrop;
#[path = "../../../../parachain/src/weights/pallet/assets.rs"]
pub mod assets;
#[path = "../../../../parachain/src/weights/pallet/balances.rs"]
pub mod balances;
#[path = "../../../../parachain/src/weights/pallet/collective.rs"]
pub mod collective;
#[path = "../../../../parachain/src/weights/pallet/doas.rs"]
pub mod doas;
#[path = "../../../../parachain/src/weights/pallet/frame_system.rs"]
pub mod frame_system;
#[path = "../../../../parachain/src/weights/pallet/hold_vesting.rs"]
pub mod hold_vesting;
#[path = "../../../../parachain/src/weights/pallet/identity.rs"]
pub mod identity;
#[path = "../../../../parachain/src/weights/pallet/im_online.rs"]
pub mod im_online;
#[path = "../../../../parachain/src/weights/pallet/membership.rs"]
pub mod membership;
#[path = "../../../../parachain/src/weights/pallet/nft_delegation.rs"]
pub mod nft_delegation;
#[path = "../../../../parachain/src/weights/pallet/nft_permission.rs"]
pub mod nft_permission;
#[path = "../../../../parachain/src/weights/pallet/nft_staking.rs"]
pub mod nft_staking;
#[path = "../../../../parachain/src/weights/pallet/nfts.rs"]
pub mod nfts;
#[path = "../../../../parachain/src/weights/pallet/parameters.rs"]
pub mod parameters;
#[path = "../../../../parachain/src/weights/pallet/preimage.rs"]
pub mod preimage;
#[path = "../../../../parachain/src/weights/pallet/proxy.rs"]
pub mod proxy;
#[path = "../../../../parachain/src/weights/pallet/recovery.rs"]
pub mod recovery;
#[path = "../../../../parachain/src/weights/pallet/scheduler.rs"]
pub mod scheduler;
#[path = "../../../../parachain/src/weights/pallet/session.rs"]
pub mod session;
#[path = "../../../../parachain/src/weights/pallet/staking_incentive.rs"]
pub mod staking_incentive;
#[path = "../../../../parachain/src/weights/pallet/timestamp.rs"]
pub mod timestamp;
#[path = "../../../../parachain/src/weights/pallet/transaction_payment.rs"]
pub mod transaction_payment;
#[path = "../../../../parachain/src/weights/pallet/treasury.rs"]
pub mod treasury;
#[path = "../../../../parachain/src/weights/pallet/utility.rs"]
pub mod utility;
#[path = "../../../../parachain/src/weights/pallet/vesting_to_freeze.rs"]
pub mod vesting_to_freeze;
